### ISSUE TITLE
Info about licensing

### ISSUE THREAD

**Issue by lucabtz** [FurkanOM/tf-rpn#1]
Hello, I'm working on a project for university with some other students and it's my first time using TensorFlow.
We're taking some of the RPN code from your repository adapting it to our needs, this code is at the repository https://github.com/ekardnam/HeadRPN
I added licensing information about your project in our readme file, not sure whether this is enough for you, we don't wanna steal anything.

Also the implementation of randomly_select_xyz_mask is genius kudos!

Sorry for bothering and thanks!

**Comment by FurkanOM** [comment]
Of course, you can use and change as you wish.
I wish you and your friends success in your project.

Also, I love randomly_select_xyz_mask method too.
I remember having a lot of fun writing this :)
Thank you for your comment 👍

**Comment by lucabtz** [comment]
Hello thanks for replying and for your wishes.

Actually the random selection of anchors is the only thing I couldn't come up with myself a previous attemp of implementation of this kinda of model.
After i discovered your code I used it as an inspiration as your implementation of all the other things was much cleaner than mine and you had that random behaviour implemented
